language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build dialog-service
  - ng build --prod
