import { NgModule } from '@angular/core'
import {
  MdcTopAppBarModule,
  MdcButtonModule,
  MdcCardModule,
  MdcChipsModule,
  MdcCheckboxModule,
  MdcDialogModule,
  MdcDrawerModule,
  MdcElevationModule,
  MdcFabModule,
  MdcFormFieldModule,
  MdcIconModule,
  MdcIconButtonModule,
  MdcLinearProgressModule,
  MdcListModule,
  MdcMenuModule,
  MdcMenuSurfaceModule,
  MdcRadioModule,
  MdcRippleModule,
  MdcSelectModule,
  MdcSliderModule,
  MdcSnackbarModule,
  MdcSwitchModule,
  MdcTextFieldModule,
  MdcTypographyModule, MdcTabModule, MdcTabScrollerModule, MdcTabBarModule
} from '@angular-mdc/web'

@NgModule({
  imports: [
    MdcTopAppBarModule,
    MdcButtonModule,
    MdcCardModule,
    MdcChipsModule,
    MdcCheckboxModule,
    MdcDialogModule,
    MdcDrawerModule,
    MdcElevationModule,
    MdcFabModule,
    MdcFormFieldModule,
    MdcIconModule,
    MdcIconButtonModule,
    MdcLinearProgressModule,
    MdcListModule,
    MdcMenuModule,
    MdcMenuSurfaceModule,
    MdcRadioModule,
    MdcRippleModule,
    MdcSelectModule,
    MdcSliderModule,
    MdcSnackbarModule,
    MdcSwitchModule,
    MdcTabBarModule,
    MdcTabModule,
    MdcTabScrollerModule,
    MdcTextFieldModule,
    MdcTypographyModule
  ],
  exports: [
    MdcTopAppBarModule,
    MdcButtonModule,
    MdcCardModule,
    MdcChipsModule,
    MdcCheckboxModule,
    MdcDialogModule,
    MdcDrawerModule,
    MdcElevationModule,
    MdcFabModule,
    MdcFormFieldModule,
    MdcIconModule,
    MdcIconButtonModule,
    MdcLinearProgressModule,
    MdcListModule,
    MdcMenuModule,
    MdcMenuSurfaceModule,
    MdcRadioModule,
    MdcRippleModule,
    MdcSelectModule,
    MdcSliderModule,
    MdcSnackbarModule,
    MdcSwitchModule,
    MdcTabBarModule,
    MdcTabModule,
    MdcTabScrollerModule,
    MdcTextFieldModule,
    MdcTypographyModule
  ]
})
export class AngularMdcModule {
  constructor () {
  }
}
